/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as ArticlesIndexRouteImport } from './routes/articles/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as ResetPasswordIndexRouteImport } from './routes/reset-password/index'
import { Route as ProtectedLoginIndexRouteImport } from './routes/_protected/login/index'
import { Route as ProtectedPostsIndexRouteImport } from './routes/_protected/posts/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedRegisterIndexRouteImport } from './routes/_protected/register/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPostsIndexRouteImport } from './routes/api/posts/index'
import { Route as ProtectedPostsCreateIndexRouteImport } from './routes/_protected/posts/create/index'
import { Route as ProtectedPostsEditPostIdRouteImport } from './routes/_protected/posts/edit/$postId'
import { Route as ApiPostsUserIdIndexRouteImport } from './routes/api/posts/$userId/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordIndexRoute = ResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLoginIndexRoute = ProtectedLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPostsIndexRoute = ProtectedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRegisterIndexRoute = ProtectedRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostsIndexRoute = ApiPostsIndexRouteImport.update({
  id: '/api/posts/',
  path: '/api/posts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPostsCreateIndexRoute =
  ProtectedPostsCreateIndexRouteImport.update({
    id: '/posts/create/',
    path: '/posts/create/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPostsEditPostIdRoute =
  ProtectedPostsEditPostIdRouteImport.update({
    id: '/posts/edit/$postId',
    path: '/posts/edit/$postId',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ApiPostsUserIdIndexRoute = ApiPostsUserIdIndexRouteImport.update({
  id: '/api/posts/$userId/',
  path: '/api/posts/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login/': typeof ProtectedLoginIndexRoute
  '/posts/': typeof ProtectedPostsIndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/register/': typeof ProtectedRegisterIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/posts/create/': typeof ProtectedPostsCreateIndexRoute
  '/api/posts/$userId/': typeof ApiPostsUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/articles': typeof ArticlesIndexRoute
  '/reset-password': typeof ResetPasswordIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/login': typeof ProtectedLoginIndexRoute
  '/posts': typeof ProtectedPostsIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/register': typeof ProtectedRegisterIndexRoute
  '/api/posts': typeof ApiPostsIndexRoute
  '/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/posts/create': typeof ProtectedPostsCreateIndexRoute
  '/api/posts/$userId': typeof ApiPostsUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/verify-email': typeof VerifyEmailRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/articles/': typeof ArticlesIndexRoute
  '/reset-password/': typeof ResetPasswordIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/login/': typeof ProtectedLoginIndexRoute
  '/_protected/posts/': typeof ProtectedPostsIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/register/': typeof ProtectedRegisterIndexRoute
  '/api/posts/': typeof ApiPostsIndexRoute
  '/_protected/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/_protected/posts/create/': typeof ProtectedPostsCreateIndexRoute
  '/api/posts/$userId/': typeof ApiPostsUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/verify-email'
    | '/posts/$postId'
    | '/articles/'
    | '/reset-password/'
    | '/api/auth/$'
    | '/login/'
    | '/posts/'
    | '/profile/'
    | '/register/'
    | '/api/posts/'
    | '/posts/edit/$postId'
    | '/posts/create/'
    | '/api/posts/$userId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/verify-email'
    | '/posts/$postId'
    | '/articles'
    | '/reset-password'
    | '/api/auth/$'
    | '/login'
    | '/posts'
    | '/profile'
    | '/register'
    | '/api/posts'
    | '/posts/edit/$postId'
    | '/posts/create'
    | '/api/posts/$userId'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/privacy-policy'
    | '/verify-email'
    | '/posts/$postId'
    | '/articles/'
    | '/reset-password/'
    | '/api/auth/$'
    | '/_protected/login/'
    | '/_protected/posts/'
    | '/_protected/profile/'
    | '/_protected/register/'
    | '/api/posts/'
    | '/_protected/posts/edit/$postId'
    | '/_protected/posts/create/'
    | '/api/posts/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  PostsPostIdRoute: typeof PostsPostIdRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ResetPasswordIndexRoute: typeof ResetPasswordIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPostsIndexRoute: typeof ApiPostsIndexRoute
  ApiPostsUserIdIndexRoute: typeof ApiPostsUserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password/': {
      id: '/reset-password/'
      path: '/reset-password'
      fullPath: '/reset-password/'
      preLoaderRoute: typeof ResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/login/': {
      id: '/_protected/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof ProtectedLoginIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/posts/': {
      id: '/_protected/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof ProtectedPostsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/register/': {
      id: '/_protected/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof ProtectedRegisterIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/posts/': {
      id: '/api/posts/'
      path: '/api/posts'
      fullPath: '/api/posts/'
      preLoaderRoute: typeof ApiPostsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/posts/create/': {
      id: '/_protected/posts/create/'
      path: '/posts/create'
      fullPath: '/posts/create/'
      preLoaderRoute: typeof ProtectedPostsCreateIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/posts/edit/$postId': {
      id: '/_protected/posts/edit/$postId'
      path: '/posts/edit/$postId'
      fullPath: '/posts/edit/$postId'
      preLoaderRoute: typeof ProtectedPostsEditPostIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/posts/$userId/': {
      id: '/api/posts/$userId/'
      path: '/api/posts/$userId'
      fullPath: '/api/posts/$userId/'
      preLoaderRoute: typeof ApiPostsUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedLoginIndexRoute: typeof ProtectedLoginIndexRoute
  ProtectedPostsIndexRoute: typeof ProtectedPostsIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedRegisterIndexRoute: typeof ProtectedRegisterIndexRoute
  ProtectedPostsEditPostIdRoute: typeof ProtectedPostsEditPostIdRoute
  ProtectedPostsCreateIndexRoute: typeof ProtectedPostsCreateIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedLoginIndexRoute: ProtectedLoginIndexRoute,
  ProtectedPostsIndexRoute: ProtectedPostsIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedRegisterIndexRoute: ProtectedRegisterIndexRoute,
  ProtectedPostsEditPostIdRoute: ProtectedPostsEditPostIdRoute,
  ProtectedPostsCreateIndexRoute: ProtectedPostsCreateIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  PostsPostIdRoute: PostsPostIdRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ResetPasswordIndexRoute: ResetPasswordIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPostsIndexRoute: ApiPostsIndexRoute,
  ApiPostsUserIdIndexRoute: ApiPostsUserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
