/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RegisterIndexRouteImport } from './routes/register/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as PostsPostIdRouteImport } from './routes/posts/$postId'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedPostsIndexRouteImport } from './routes/_protected/posts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedPostsCreateIndexRouteImport } from './routes/_protected/posts/create/index'
import { Route as ProtectedPostsEditPostIdRouteImport } from './routes/_protected/posts/edit/$postId'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterIndexRoute = RegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPostsIndexRoute = ProtectedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPostsCreateIndexRoute =
  ProtectedPostsCreateIndexRouteImport.update({
    id: '/posts/create/',
    path: '/posts/create/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPostsEditPostIdRoute =
  ProtectedPostsEditPostIdRouteImport.update({
    id: '/posts/edit/$postId',
    path: '/posts/edit/$postId',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts/': typeof ProtectedPostsIndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/posts/create/': typeof ProtectedPostsCreateIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/posts/$postId': typeof PostsPostIdRoute
  '/login': typeof LoginIndexRoute
  '/register': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/posts': typeof ProtectedPostsIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/posts/create': typeof ProtectedPostsCreateIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/login/': typeof LoginIndexRoute
  '/register/': typeof RegisterIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/posts/': typeof ProtectedPostsIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/posts/edit/$postId': typeof ProtectedPostsEditPostIdRoute
  '/_protected/posts/create/': typeof ProtectedPostsCreateIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/posts/$postId'
    | '/login/'
    | '/register/'
    | '/api/auth/$'
    | '/posts/'
    | '/profile/'
    | '/posts/edit/$postId'
    | '/posts/create/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/posts/$postId'
    | '/login'
    | '/register'
    | '/api/auth/$'
    | '/posts'
    | '/profile'
    | '/posts/edit/$postId'
    | '/posts/create'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/posts/$postId'
    | '/login/'
    | '/register/'
    | '/api/auth/$'
    | '/_protected/posts/'
    | '/_protected/profile/'
    | '/_protected/posts/edit/$postId'
    | '/_protected/posts/create/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
  LoginIndexRoute: typeof LoginIndexRoute
  RegisterIndexRoute: typeof RegisterIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/': {
      id: '/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof RegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/posts/': {
      id: '/_protected/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof ProtectedPostsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/posts/create/': {
      id: '/_protected/posts/create/'
      path: '/posts/create'
      fullPath: '/posts/create/'
      preLoaderRoute: typeof ProtectedPostsCreateIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/posts/edit/$postId': {
      id: '/_protected/posts/edit/$postId'
      path: '/posts/edit/$postId'
      fullPath: '/posts/edit/$postId'
      preLoaderRoute: typeof ProtectedPostsEditPostIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedPostsIndexRoute: typeof ProtectedPostsIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedPostsEditPostIdRoute: typeof ProtectedPostsEditPostIdRoute
  ProtectedPostsCreateIndexRoute: typeof ProtectedPostsCreateIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPostsIndexRoute: ProtectedPostsIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedPostsEditPostIdRoute: ProtectedPostsEditPostIdRoute,
  ProtectedPostsCreateIndexRoute: ProtectedPostsCreateIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
  LoginIndexRoute: LoginIndexRoute,
  RegisterIndexRoute: RegisterIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
